/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	osmconfigv1 "github.com/open-service-mesh/osm/pkg/apis/osmconfig/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeOSMConfigs implements OSMConfigInterface
type FakeOSMConfigs struct {
	Fake *FakeOsmV1
	ns   string
}

var osmconfigsResource = schema.GroupVersionResource{Group: "osm.k8s.io", Version: "v1", Resource: "osmconfigs"}

var osmconfigsKind = schema.GroupVersionKind{Group: "osm.k8s.io", Version: "v1", Kind: "OSMConfig"}

// Get takes name of the oSMConfig, and returns the corresponding oSMConfig object, and an error if there is any.
func (c *FakeOSMConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *osmconfigv1.OSMConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(osmconfigsResource, c.ns, name), &osmconfigv1.OSMConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*osmconfigv1.OSMConfig), err
}

// List takes label and field selectors, and returns the list of OSMConfigs that match those selectors.
func (c *FakeOSMConfigs) List(ctx context.Context, opts v1.ListOptions) (result *osmconfigv1.OSMConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(osmconfigsResource, osmconfigsKind, c.ns, opts), &osmconfigv1.OSMConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &osmconfigv1.OSMConfigList{ListMeta: obj.(*osmconfigv1.OSMConfigList).ListMeta}
	for _, item := range obj.(*osmconfigv1.OSMConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested oSMConfigs.
func (c *FakeOSMConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(osmconfigsResource, c.ns, opts))

}

// Create takes the representation of a oSMConfig and creates it.  Returns the server's representation of the oSMConfig, and an error, if there is any.
func (c *FakeOSMConfigs) Create(ctx context.Context, oSMConfig *osmconfigv1.OSMConfig, opts v1.CreateOptions) (result *osmconfigv1.OSMConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(osmconfigsResource, c.ns, oSMConfig), &osmconfigv1.OSMConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*osmconfigv1.OSMConfig), err
}

// Update takes the representation of a oSMConfig and updates it. Returns the server's representation of the oSMConfig, and an error, if there is any.
func (c *FakeOSMConfigs) Update(ctx context.Context, oSMConfig *osmconfigv1.OSMConfig, opts v1.UpdateOptions) (result *osmconfigv1.OSMConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(osmconfigsResource, c.ns, oSMConfig), &osmconfigv1.OSMConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*osmconfigv1.OSMConfig), err
}

// Delete takes name of the oSMConfig and deletes it. Returns an error if one occurs.
func (c *FakeOSMConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(osmconfigsResource, c.ns, name), &osmconfigv1.OSMConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeOSMConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(osmconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &osmconfigv1.OSMConfigList{})
	return err
}

// Patch applies the patch and returns the patched oSMConfig.
func (c *FakeOSMConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *osmconfigv1.OSMConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(osmconfigsResource, c.ns, name, pt, data, subresources...), &osmconfigv1.OSMConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*osmconfigv1.OSMConfig), err
}
