apiVersion: config.openservicemesh.io/v1alpha1
kind: MeshConfig
metadata:
  name: osm-mesh-config
spec:
  sidecar:
    enablePriviledgedInitContainer: false
    logLevel: error
    maxDataPlaneConnections: 0
  traffic:
    enableEgress: false
    useHTTPSIngress: false
    enablePermissiveTrafficPolicyMode: true
  observability:
    enableDebugServer: true
    prometheusScraping: true
    tracing:
      enable: false
  certificate:
    serviceCertValidityDuration: 24h

