/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/open-service-mesh/osm/pkg/apis/osmbackpressureconfig/v1"
	scheme "github.com/open-service-mesh/osm/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// OSMBackpressureConfigsGetter has a method to return a OSMBackpressureConfigInterface.
// A group's client should implement this interface.
type OSMBackpressureConfigsGetter interface {
	OSMBackpressureConfigs(namespace string) OSMBackpressureConfigInterface
}

// OSMBackpressureConfigInterface has methods to work with OSMBackpressureConfig resources.
type OSMBackpressureConfigInterface interface {
	Create(ctx context.Context, oSMBackpressureConfig *v1.OSMBackpressureConfig, opts metav1.CreateOptions) (*v1.OSMBackpressureConfig, error)
	Update(ctx context.Context, oSMBackpressureConfig *v1.OSMBackpressureConfig, opts metav1.UpdateOptions) (*v1.OSMBackpressureConfig, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.OSMBackpressureConfig, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.OSMBackpressureConfigList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.OSMBackpressureConfig, err error)
	OSMBackpressureConfigExpansion
}

// oSMBackpressureConfigs implements OSMBackpressureConfigInterface
type oSMBackpressureConfigs struct {
	client rest.Interface
	ns     string
}

// newOSMBackpressureConfigs returns a OSMBackpressureConfigs
func newOSMBackpressureConfigs(c *OsmbackpressureconfigV1Client, namespace string) *oSMBackpressureConfigs {
	return &oSMBackpressureConfigs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the oSMBackpressureConfig, and returns the corresponding oSMBackpressureConfig object, and an error if there is any.
func (c *oSMBackpressureConfigs) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.OSMBackpressureConfig, err error) {
	result = &v1.OSMBackpressureConfig{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("osmbackpressureconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of OSMBackpressureConfigs that match those selectors.
func (c *oSMBackpressureConfigs) List(ctx context.Context, opts metav1.ListOptions) (result *v1.OSMBackpressureConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.OSMBackpressureConfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("osmbackpressureconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested oSMBackpressureConfigs.
func (c *oSMBackpressureConfigs) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("osmbackpressureconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a oSMBackpressureConfig and creates it.  Returns the server's representation of the oSMBackpressureConfig, and an error, if there is any.
func (c *oSMBackpressureConfigs) Create(ctx context.Context, oSMBackpressureConfig *v1.OSMBackpressureConfig, opts metav1.CreateOptions) (result *v1.OSMBackpressureConfig, err error) {
	result = &v1.OSMBackpressureConfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("osmbackpressureconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(oSMBackpressureConfig).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a oSMBackpressureConfig and updates it. Returns the server's representation of the oSMBackpressureConfig, and an error, if there is any.
func (c *oSMBackpressureConfigs) Update(ctx context.Context, oSMBackpressureConfig *v1.OSMBackpressureConfig, opts metav1.UpdateOptions) (result *v1.OSMBackpressureConfig, err error) {
	result = &v1.OSMBackpressureConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("osmbackpressureconfigs").
		Name(oSMBackpressureConfig.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(oSMBackpressureConfig).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the oSMBackpressureConfig and deletes it. Returns an error if one occurs.
func (c *oSMBackpressureConfigs) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("osmbackpressureconfigs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *oSMBackpressureConfigs) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("osmbackpressureconfigs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched oSMBackpressureConfig.
func (c *oSMBackpressureConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.OSMBackpressureConfig, err error) {
	result = &v1.OSMBackpressureConfig{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("osmbackpressureconfigs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
