// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openservicemesh/osm/pkg/ingress (interfaces: Monitor)

// Package ingress is a generated GoMock package.
package ingress

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	"github.com/openservicemesh/osm/pkg/announcements"
	service "github.com/openservicemesh/osm/pkg/service"
	v1beta1 "k8s.io/api/extensions/v1beta1"
)

// MockMonitor is a mock of Monitor interface
type MockMonitor struct {
	ctrl     *gomock.Controller
	recorder *MockMonitorMockRecorder
}

// MockMonitorMockRecorder is the mock recorder for MockMonitor
type MockMonitorMockRecorder struct {
	mock *MockMonitor
}

// NewMockMonitor creates a new mock instance
func NewMockMonitor(ctrl *gomock.Controller) *MockMonitor {
	mock := &MockMonitor{ctrl: ctrl}
	mock.recorder = &MockMonitorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMonitor) EXPECT() *MockMonitorMockRecorder {
	return m.recorder
}

// GetAnnouncementsChannel mocks base method
func (m *MockMonitor) GetAnnouncementsChannel() <-chan announcements.Announcement {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnnouncementsChannel")
	ret0, _ := ret[0].(<-chan announcements.Announcement)
	return ret0
}

// GetAnnouncementsChannel indicates an expected call of GetAnnouncementsChannel
func (mr *MockMonitorMockRecorder) GetAnnouncementsChannel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnnouncementsChannel", reflect.TypeOf((*MockMonitor)(nil).GetAnnouncementsChannel))
}

// GetIngressResources mocks base method
func (m *MockMonitor) GetIngressResources(arg0 service.MeshService) ([]*v1beta1.Ingress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIngressResources", arg0)
	ret0, _ := ret[0].([]*v1beta1.Ingress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIngressResources indicates an expected call of GetIngressResources
func (mr *MockMonitorMockRecorder) GetIngressResources(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIngressResources", reflect.TypeOf((*MockMonitor)(nil).GetIngressResources), arg0)
}
