run:
  tests: true

linters:
  enable:
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - golint
    - govet
    - misspell
    - unused
    - whitespace

linters-settings:
  goimports:
    local-prefixes: github.com/openservicemesh/osm

issues:
  new: true
  exclude-rules:
    - linters:
        - golint
      source: ". \"github.com/onsi/(ginkgo|gomega)\""
      text: "dot imports"

