run:
  tests: true
  timeout: 20m
  skip-dirs:
    - pkg/gen
  skip-files:
    - "zz_generated.deepcopy.go$"

linters:
  disable-all: true
  enable:
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - govet
    - misspell
    - revive
    - unused
    - whitespace

linters-settings:
  goimports:
    local-prefixes: github.com/openservicemesh/osm
  revive:
    ignore-generated-header: false
    severity: "warning"
    confidence: 0.0
    error-code: 2
    warning-code: 1

issues:
  exclude-rules:
    # Ignore error for ginkgo and gomega dot imports
    - linters:
        - revive
      source: ". \"github.com/onsi/(ginkgo|gomega)\""
      text: "dot imports"
    # Ignore error for test framework imports
    - linters:
        - revive
      source: ". \"github.com/openservicemesh/osm/tests/framework\""
      text: "dot imports"
    # Ignore error for package comments
    - linters:
        - revive
      text: "package-comments: should have a package comment"
    # Exclude staticcheck messages for deprecated function, variable or constant
    # This causes issues with package github.com/golang/protobuf/proto
    - linters:
        - staticcheck
      text: "SA1019:"
  exclude-use-default: false

