run:
  tests: true

issues:
  new: true

linters:
  enable:
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - golint
    - govet
    - misspell
    - unused
    - whitespace

linters-settings:
  goimports:
    local-prefixes: github.com/openservicemesh/osm
