// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openservicemesh/osm/pkg/kubernetes (interfaces: NamespaceController)

// Package namespace is a generated GoMock package.
package kubernetes

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNamespaceController is a mock of NamespaceController interface
type MockNamespaceController struct {
	ctrl     *gomock.Controller
	recorder *MockNamespaceControllerMockRecorder
}

// MockNamespaceControllerMockRecorder is the mock recorder for MockController
type MockNamespaceControllerMockRecorder struct {
	mock *MockNamespaceController
}

// NewMockController creates a new mock instance
func NewMockNamespaceController(ctrl *gomock.Controller) *MockNamespaceController {
	mock := &MockNamespaceController{ctrl: ctrl}
	mock.recorder = &MockNamespaceControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockNamespaceController) EXPECT() *MockNamespaceControllerMockRecorder {
	return m.recorder
}

// GetAnnouncementsChannel mocks base method
func (m *MockNamespaceController) GetAnnouncementsChannel() <-chan interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnnouncementsChannel")
	ret0, _ := ret[0].(<-chan interface{})
	return ret0
}

// GetAnnouncementsChannel indicates an expected call of GetAnnouncementsChannel
func (mr *MockNamespaceControllerMockRecorder) GetAnnouncementsChannel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnnouncementsChannel", reflect.TypeOf((*MockNamespaceController)(nil).GetAnnouncementsChannel))
}

// IsMonitoredNamespace mocks base method
func (m *MockNamespaceController) IsMonitoredNamespace(arg0 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMonitoredNamespace", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsMonitoredNamespace indicates an expected call of IsMonitoredNamespace
func (mr *MockNamespaceControllerMockRecorder) IsMonitoredNamespace(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMonitoredNamespace", reflect.TypeOf((*MockNamespaceController)(nil).IsMonitoredNamespace), arg0)
}

// ListMonitoredNamespaces mocks base method
func (m *MockNamespaceController) ListMonitoredNamespaces() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMonitoredNamespaces")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMonitoredNamespaces indicates an expected call of ListMonitoredNamespaces
func (mr *MockNamespaceControllerMockRecorder) ListMonitoredNamespaces() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMonitoredNamespaces", reflect.TypeOf((*MockNamespaceController)(nil).ListMonitoredNamespaces))
}
