apiVersion: v1
kind: Service
metadata:
  name: bookstore-mesh
  namespace: bookstore-ns
  labels:
    app: bookstore-mesh
spec:
  ports:
  - port: 8080
    name: bookstore-port
  selector:
    app: bookstore-mesh
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-v1
  namespace: bookstore-ns
  labels:
    app: bookstore-v1
spec:
  ports:
  - port: 8080
    name: bookstore-port
  selector:
    app: bookstore-v1
