apiVersion: v1
kind: Service
metadata:
  name: bookbuyer
  namespace: bookbuyer-ns
  labels:
    app: bookbuyer
spec:
  ports:
  - port: 9999
    name: dummy-unused-port
  selector:
    app: bookbuyer
