{{- if .Values.OpenServiceMesh.deployGrafana}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: osm-grafana-config
  namespace: {{ include "osm.namespace" . }}
  labels:
    app: osm-grafana
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: osm-grafana-datasources
  namespace: {{ include "osm.namespace" . }}
  labels:
    app: osm-grafana
data:
  prometheus.yaml: |
    # config file version
    apiVersion: 1

    # list of datasources that should be deleted from the database
    deleteDatasources:
      - name: Prometheus
        orgId: 1

    # list of datasources to insert/update depending
    # whats available in the database
    datasources:
      # <string, required> name of the datasource. Required
      - name: Prometheus
        # <string, required> datasource type. Required
        type: prometheus
        # <string, required> access mode. direct or proxy. Required
        access: proxy
        # <int> org id. will default to orgId 1 if not specified
        orgId: 1
        # <string> url
        url: http://osm-prometheus.{{ include "osm.namespace" . }}.svc:{{.Values.OpenServiceMesh.prometheus.port}}
        version: 1
        # <bool> allow users to edit datasources from the UI.
        editable: true

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: osm-grafana-dashboard-definition-dataplane
  namespace: {{ include "osm.namespace" . }}
  labels:
    app: osm-grafana
data:
  osm-pod.json: |
{{ .Files.Get "grafana/dashboards/osm-pod.json" | replace "${DS_PROMETHEUS}" "Prometheus" | indent 4 }}
  osm-workload.json: |
{{ .Files.Get "grafana/dashboards/osm-workload.json" | replace "${DS_PROMETHEUS}" "Prometheus" | indent 4 }}
  osm-service-to-service.json: |
{{ .Files.Get "grafana/dashboards/osm-service-to-service.json" | replace "${DS_PROMETHEUS}" "Prometheus" | indent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: osm-grafana-dashboard-definition-controlplane
  namespace: {{ include "osm.namespace" . }}
  labels:
    app: osm-grafana
data:
  osm-control-plane.json: |
{{ .Files.Get "grafana/dashboards/osm-control-plane.json" | replace "${DS_PROMETHEUS}" "Prometheus" | indent 4 }}
  osm-mesh-envoy-details.json: |
{{ .Files.Get "grafana/dashboards/osm-mesh-envoy-details.json" | replace "${DS_PROMETHEUS}" "Prometheus" | indent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: osm-grafana-dashboards
  namespace: {{ include "osm.namespace" . }}
  labels:
    app: osm-grafana
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: 'OSM Data Plane'
      orgId: 1
      folder: 'OSM Data Plane'
      type: file
      disableDeletion: false
      editable: true
      updateIntervalSeconds: 10
      options:
        path: /etc/grafana/provisioning/dashboards/dataplane
    - name: 'OSM Control Plane'
      orgId: 1
      folder: 'OSM Control Plane'
      type: file
      disableDeletion: false
      editable: true
      updateIntervalSeconds: 10
      options:
        path: /etc/grafana/provisioning/dashboards/controlplane
{{- end }}