apiVersion: v1
kind: ConfigMap
metadata:
  name: osm-grafana-config
  labels:
    app: osm-grafana
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: osm-grafana-datasources
  labels:
    app: osm-grafana
data:
  prometheus.yaml: |
    # config file version
    apiVersion: 1

    # list of datasources that should be deleted from the database
    deleteDatasources:
      - name: Prometheus
        orgId: 1

    # list of datasources to insert/update depending
    # whats available in the database
    datasources:
      # <string, required> name of the datasource. Required
      - name: Prometheus
        # <string, required> datasource type. Required
        type: prometheus
        # <string, required> access mode. direct or proxy. Required
        access: proxy
        # <int> org id. will default to orgId 1 if not specified
        orgId: 1
        # <string> url
        url: http://osm-prometheus.{{.Release.Name}}.svc:{{.Values.prometheus.port}}
        version: 1
        # <bool> allow users to edit datasources from the UI.
        editable: true