{{- if .Values.OpenServiceMesh.featureFlags.enableOSMGateway }}
---
kind: Secret
apiVersion: v1
metadata:
  name: osm-gateway-bootstrap-config
  namespace: {{ include "osm.namespace" . }}
  labels:
    app: osm-gateway
type: Opaque
stringData:
  bootstrap.yaml: "-- placeholder --"
{{- end }}