{{- if .Values.osm.featureFlags.enableMulticlusterMode }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: osm-multicluster-gateway
  namespace: {{ include "osm.namespace" . }}
  labels:
    app: osm-multicluster-gateway
spec:
  selector:
    matchLabels:
      app: osm-multicluster-gateway
  template:
    metadata:
      labels:
        app: osm-multicluster-gateway
      name: osm-multicluster-gateway
    spec:
      serviceAccountName: {{ .Release.Name }}
      initContainers:
        - name: osm-multicluster-gateway-init
          image: {{ .Values.osm.curlImage }}
          args:
          - /bin/sh
          - -c
          - >
            set -x;
            while [ $(curl -sw '%{http_code}' "http://osm-controller.{{ include "osm.namespace" . }}.svc.cluster.local:9091/health/ready" -o /dev/null) -ne 200 ]; do
              sleep 10;
            done
      containers:
        - name: envoy
          image: {{ .Values.osm.sidecarImage }}
          command:
            - "envoy"
          args: [
            "--config-path", "/etc/envoy/bootstrap.yaml",
            "--service-node", "osm-multicluster-gateway",
            "--service-cluster", "osm-multicluster-gateway",
            "--log-level", {{ .Values.osm.multicluster.gatewayLogLevel }},
          ]
          ports:
            - name: "multicluster"
              containerPort: 15443
          volumeMounts:
            - name: envoy-bootstrap-config-volume
              mountPath: /etc/envoy
              readOnly: true
      volumes:
        - name: envoy-bootstrap-config-volume
          secret:
            secretName: osm-multicluster-gateway-bootstrap-config
      {{- if .Values.osm.multicluster.affinity }}
      affinity:
      {{- toYaml .Values.osm.multicluster.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.osm.multicluster.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.osm.multicluster.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.osm.multicluster.tolerations }}
      tolerations:
      {{- toYaml .Values.osm.multicluster.tolerations | nindent 8 }}
      {{- end }}
{{- end }}