{{- if .Values.osm.featureFlags.enableMulticlusterMode }}
---
kind: Secret
apiVersion: v1
metadata:
  name: osm-multicluster-gateway-bootstrap-config
  namespace: {{ include "osm.namespace" . }}
  labels:
    app: osm-multicluster-gateway
type: Opaque
stringData:
  bootstrap.yaml: "-- placeholder --"
{{- end }}