{{- if .Values.OpenServiceMesh.injector.autoScale.enable }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: osm-injector-hpa
  namespace: {{ include "osm.namespace" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: osm-injector
  minReplicas: {{.Values.OpenServiceMesh.injector.autoScale.minReplicas}}
  maxReplicas: {{.Values.OpenServiceMesh.injector.autoScale.maxReplicas}}
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageValue: {{.Values.OpenServiceMesh.injector.autoScale.memory.targetAverageValue}}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{.Values.OpenServiceMesh.injector.autoScale.cpu.targetAverageUtilization}}
{{- end }}
