apiVersion: v1
kind: Service
metadata:
  name: osm-injector
  namespace: {{ include "osm.namespace" . }}
  labels:
    app: osm-injector
spec:
  ports:
    - name: sidecar-inject
      port: 9090
  selector:
    app: osm-injector