apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-preinstall
  namespace: {{ include "osm.namespace" . }}
  labels:
    {{- include "osm.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-preinstall
  namespace: {{ include "osm.namespace" . }}
  labels:
    {{- include "osm.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-preinstall
    namespace: {{ include "osm.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-preinstall
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-preinstall
  namespace: {{ include "osm.namespace" . }}
  labels:
    {{- include "osm.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-preinstall
  namespace: {{ include "osm.namespace" . }}
  labels:
    {{- include "osm.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backoffLimit: 0
  template:
    metadata:
      name: {{ .Release.Name }}-preinstall
      labels:
        {{- include "osm.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}-preinstall
      restartPolicy: Never
      containers:
        - name: preinstall
          image: "{{ include "osmPreinstall.image" . }}"
          imagePullPolicy: {{ .Values.osm.image.pullPolicy }}
          command: ['/osm-preinstall']
          args:
            - --verbosity={{ .Values.osm.controllerLogLevel }}
            - --enforce-single-mesh={{ .Values.osm.enforceSingleMesh }}
            - --namespace={{ include "osm.namespace" . }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
                    - arm64
{{- if .Values.osm.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.osm.imagePullSecrets | indent 8 }}
{{- end }}
