{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: osm-controller
  namespace: {{ template "osm.namespace" . }}
  labels:
    {{- include "osm.labels" . | nindent 4 }}
    {{- if .Values.serviceMonitor.additionalLabels }}
    {{ toYaml .Values.serviceMonitor.additionalLabels }}
    {{- end }}
spec:
  jobLabel: osm-controller
  endpoints:
    - port: healthz
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      {{- if .Values.serviceMonitor.honorLabels }}
      honorLabels: true
      {{- end }}
  selector:
    matchLabels:
      app: osm-controller
{{- end }}
