apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app: osm-controller
  name: {{.Values.OpenServiceMesh.webhookConfigNamePrefix}}-{{.Values.OpenServiceMesh.meshName}}
webhooks:
- name: validating-webhook.k8s.io
  clientConfig:
    service:
      name: osm-controller
      namespace: {{.Release.Namespace}}
      path: /validate-webhook
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  namespaceSelector:
    matchLabels:
      name: osm-system
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - v1
      operations:
        - CREATE
        - UPDATE
        - DELETE
      resources:
        - configmaps
