// Package featureflags implements routines to check if a given feature is enabled.
package featureflags

import (
	"sync"
)

// OptionalFeatures is a struct to enable/disable optional features
type OptionalFeatures struct {
	WASMStats bool
}

var (
	// Features describes whether an optional feature is enabled
	Features OptionalFeatures

	once sync.Once
)

// Initialize initializes the feature flag options
func Initialize(optionalFeatures OptionalFeatures) {
	once.Do(func() {
		Features = optionalFeatures
	})
}

/* Feature flag stub
// IsFeatureNameEnabled returns a boolean indicating if the feature `FeatureName` is enabled
func IsFeatureNameEnabled() bool {
	return Features.FeatureName
}
*/

// IsWASMStatsEnabled returns a boolean indicating if custom stats will be generated by a WASM extension to Envoy
func IsWASMStatsEnabled() bool {
	return Features.WASMStats
}
