apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: backpressures.policy.openservicemesh.io
spec:
  group: policy.openservicemesh.io
  version: v1alpha1
  names:
    kind: Backpressure
    plural: backpressures
    singular: backpressure
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            maxConnections:
              description: "Max number of connections"
              type: integer
              pattern: '^[1-9]{1}[0-9]*'
