# Current build against rev 956f0d500c380cc1656a2d861b7ee12c2515a664 of https://github.com/proxy-wasm/proxy-wasm-cpp-sdk
# Docker image: openservicemesh/proxy-wasm-cpp-sdk:956f0d500c380cc1656a2d861b7ee12c2515a664

PROXY_WASM_CPP_SDK=/sdk

all: stats.wasm

include ${PROXY_WASM_CPP_SDK}/Makefile.base_lite

