apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: http-split
  namespace: httpbin
spec:
  service: httpbin.httpbin
  backends:
  - service: httpbin-v1
    weight: 50
  - service: httpbin-v2
    weight: 50
