FROM alpine:3.10.1
RUN apk add --update --no-cache tcpdump iproute2 lsof conntrack-tools tshark htop iftop curl iptables
ADD ./demo/bin/bookthief /
ADD ./demo/bookthief.html.template /
WORKDIR /
EXPOSE 8080
RUN chmod +x bookthief
