FROM alpine:3.10.1
RUN apk add --update --no-cache tcpdump iproute2 lsof conntrack-tools tshark htop iftop curl iptables
ADD ./demo/bin/bookstore /
ADD ./demo/bookstore.html.template /
WORKDIR /
EXPOSE 8080
RUN chmod +x bookstore
