FROM alpine:3.10.1
RUN apk --update --no-cache add curl
RUN apk add --no-cache iptables
ADD ./demo/bin/bookstore /
ADD ./demo/bookstore.html.template /
WORKDIR /
RUN chmod +x bookstore
CMD ["sh","bookstore"]
