apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: multiclusterservices.config.openservicemesh.io
spec:
  group: config.openservicemesh.io
  scope: Namespaced # osm-system is the required namespace
  names:
    kind: MultiClusterService
    shortNames:
      - mcs
    plural: multiclusterservices
    singular: multiclusterservice
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - serviceAccount
                - clusters
              properties:
                serviceAccount:
                  type: string
                clusters:
                  description: The clusters the service accounts are hosted on.
                  type: array
                  items:
                    type: object
                    required:
                      - address
                      - name
                    properties:
                      address:
                        description: a routable IP + port
                        type: string
                      name:
                        description: Name of the remote cluster
                        type: string
                      certificate:
                        description: mTLS certificates (optional)
                        type: string
