/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/deislabs/smc/pkg/apis/azureresource/v1"
	scheme "github.com/deislabs/smc/pkg/smc_client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AzureResourcesGetter has a method to return a AzureResourceInterface.
// A group's client should implement this interface.
type AzureResourcesGetter interface {
	AzureResources(namespace string) AzureResourceInterface
}

// AzureResourceInterface has methods to work with AzureResource resources.
type AzureResourceInterface interface {
	Create(*v1.AzureResource) (*v1.AzureResource, error)
	Update(*v1.AzureResource) (*v1.AzureResource, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.AzureResource, error)
	List(opts metav1.ListOptions) (*v1.AzureResourceList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AzureResource, err error)
	AzureResourceExpansion
}

// azureResources implements AzureResourceInterface
type azureResources struct {
	client rest.Interface
	ns     string
}

// newAzureResources returns a AzureResources
func newAzureResources(c *SmcV1Client, namespace string) *azureResources {
	return &azureResources{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the azureResource, and returns the corresponding azureResource object, and an error if there is any.
func (c *azureResources) Get(name string, options metav1.GetOptions) (result *v1.AzureResource, err error) {
	result = &v1.AzureResource{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("azureresources").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AzureResources that match those selectors.
func (c *azureResources) List(opts metav1.ListOptions) (result *v1.AzureResourceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.AzureResourceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("azureresources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested azureResources.
func (c *azureResources) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("azureresources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a azureResource and creates it.  Returns the server's representation of the azureResource, and an error, if there is any.
func (c *azureResources) Create(azureResource *v1.AzureResource) (result *v1.AzureResource, err error) {
	result = &v1.AzureResource{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("azureresources").
		Body(azureResource).
		Do().
		Into(result)
	return
}

// Update takes the representation of a azureResource and updates it. Returns the server's representation of the azureResource, and an error, if there is any.
func (c *azureResources) Update(azureResource *v1.AzureResource) (result *v1.AzureResource, err error) {
	result = &v1.AzureResource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("azureresources").
		Name(azureResource.Name).
		Body(azureResource).
		Do().
		Into(result)
	return
}

// Delete takes name of the azureResource and deletes it. Returns an error if one occurs.
func (c *azureResources) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("azureresources").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *azureResources) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("azureresources").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched azureResource.
func (c *azureResources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AzureResource, err error) {
	result = &v1.AzureResource{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("azureresources").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
