/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	azureresourcev1 "github.com/open-service-mesh/osm/pkg/apis/azureresource/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAzureResources implements AzureResourceInterface
type FakeAzureResources struct {
	Fake *FakeSmcV1
	ns   string
}

var azureresourcesResource = schema.GroupVersionResource{Group: "smc.osm.k8s.io", Version: "v1", Resource: "azureresources"}

var azureresourcesKind = schema.GroupVersionKind{Group: "smc.osm.k8s.io", Version: "v1", Kind: "AzureResource"}

// Get takes name of the azureResource, and returns the corresponding azureResource object, and an error if there is any.
func (c *FakeAzureResources) Get(name string, options v1.GetOptions) (result *azureresourcev1.AzureResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(azureresourcesResource, c.ns, name), &azureresourcev1.AzureResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*azureresourcev1.AzureResource), err
}

// List takes label and field selectors, and returns the list of AzureResources that match those selectors.
func (c *FakeAzureResources) List(opts v1.ListOptions) (result *azureresourcev1.AzureResourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(azureresourcesResource, azureresourcesKind, c.ns, opts), &azureresourcev1.AzureResourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &azureresourcev1.AzureResourceList{ListMeta: obj.(*azureresourcev1.AzureResourceList).ListMeta}
	for _, item := range obj.(*azureresourcev1.AzureResourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested azureResources.
func (c *FakeAzureResources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(azureresourcesResource, c.ns, opts))

}

// Create takes the representation of a azureResource and creates it.  Returns the server's representation of the azureResource, and an error, if there is any.
func (c *FakeAzureResources) Create(azureResource *azureresourcev1.AzureResource) (result *azureresourcev1.AzureResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(azureresourcesResource, c.ns, azureResource), &azureresourcev1.AzureResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*azureresourcev1.AzureResource), err
}

// Update takes the representation of a azureResource and updates it. Returns the server's representation of the azureResource, and an error, if there is any.
func (c *FakeAzureResources) Update(azureResource *azureresourcev1.AzureResource) (result *azureresourcev1.AzureResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(azureresourcesResource, c.ns, azureResource), &azureresourcev1.AzureResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*azureresourcev1.AzureResource), err
}

// Delete takes name of the azureResource and deletes it. Returns an error if one occurs.
func (c *FakeAzureResources) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(azureresourcesResource, c.ns, name), &azureresourcev1.AzureResource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAzureResources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(azureresourcesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &azureresourcev1.AzureResourceList{})
	return err
}

// Patch applies the patch and returns the patched azureResource.
func (c *FakeAzureResources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *azureresourcev1.AzureResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(azureresourcesResource, c.ns, name, pt, data, subresources...), &azureresourcev1.AzureResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*azureresourcev1.AzureResource), err
}
