apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: backpressureconfigs.envoy.openservicemesh.io
spec:
  group: envoy.openservicemesh.io
  version: v1
  names:
    kind: BackpressureConfig
    plural: backpressureconfigs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            maxRequestsPerConnection:
              description: "Max number per connection"
              type: integer
              pattern: '^[1-9]{1}[0-9]*'