apiVersion: v1
kind: Service
metadata:
  name: bookthief
  labels:
    app: bookthief
spec:
  type: {{ .Values.service.type }}
  ports:
{{ toYaml .Values.service.ports | indent 4 }}
  selector:
    app: bookthief
