/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	osmconfigv1 "github.com/open-service-mesh/osm/pkg/apis/osmconfig/v1"
	versioned "github.com/open-service-mesh/osm/pkg/client/clientset/versioned"
	internalinterfaces "github.com/open-service-mesh/osm/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/open-service-mesh/osm/pkg/client/listers/osmconfig/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// OSMConfigInformer provides access to a shared informer and lister for
// OSMConfigs.
type OSMConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.OSMConfigLister
}

type oSMConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewOSMConfigInformer constructs a new informer for OSMConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewOSMConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredOSMConfigInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredOSMConfigInformer constructs a new informer for OSMConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredOSMConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OsmV1().OSMConfigs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OsmV1().OSMConfigs(namespace).Watch(context.TODO(), options)
			},
		},
		&osmconfigv1.OSMConfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *oSMConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredOSMConfigInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *oSMConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&osmconfigv1.OSMConfig{}, f.defaultInformer)
}

func (f *oSMConfigInformer) Lister() v1.OSMConfigLister {
	return v1.NewOSMConfigLister(f.Informer().GetIndexer())
}
