# This manifest is required the demonstrate the usage of permissive traffic policy mode in OSM.
# It has the resource specs for the 'bookstore' ServiceAccount, and Deployment.
---
# Deploy bookstore Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookstore
  namespace: bookstore
---
# Deploy bookstore Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore
  template:
    metadata:
      labels:
        app: bookstore
        version: v1
    spec:
      serviceAccountName: bookstore
      containers:
        - name: bookstore
          image: openservicemesh/bookstore:v0.2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: web
          command: ["/bookstore"]
          args: ["--path", "./", "--port", "80"]
          env:
            - name: BOOKWAREHOUSE_NAMESPACE
              value: bookwarehouse
            - name: IDENTITY
              value: bookstore-v1
