apiVersion: apps/v1
kind: Deployment
metadata:
  name: addapp
  namespace: calculator
  labels:
    app: add
spec:
  replicas: 1
  selector:
    matchLabels:
      app: add
  template:
    metadata:
      labels:
        app: add
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "addapp"
        dapr.io/port: "6000"
        dapr.io/config: "appconfig"
    spec:
      containers:
      - name: add
        image: dapriosamples/distributed-calculator-go:edge
        ports:
        - containerPort: 6000
        imagePullPolicy: Always
