apiVersion: apps/v1
kind: Deployment
metadata:
  name: divideapp
  namespace: calculator
  labels:
    app: divide
spec:
  replicas: 1
  selector:
    matchLabels:
      app: divide
  template:
    metadata:
      labels:
        app: divide
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "divideapp"
        dapr.io/port: "4000"
        dapr.io/config: "appconfig"
    spec:
      containers:
      - name: divide
        image: dapriosamples/distributed-calculator-node:edge
        ports:
        - containerPort: 4000
        imagePullPolicy: Always
