/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/openservicemesh/osm/experimental/pkg/apis/policy/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBackpressures implements BackpressureInterface
type FakeBackpressures struct {
	Fake *FakePolicyV1alpha1
	ns   string
}

var backpressuresResource = schema.GroupVersionResource{Group: "policy.openservicemesh.io", Version: "v1alpha1", Resource: "backpressures"}

var backpressuresKind = schema.GroupVersionKind{Group: "policy.openservicemesh.io", Version: "v1alpha1", Kind: "Backpressure"}

// Get takes name of the backpressure, and returns the corresponding backpressure object, and an error if there is any.
func (c *FakeBackpressures) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Backpressure, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(backpressuresResource, c.ns, name), &v1alpha1.Backpressure{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Backpressure), err
}

// List takes label and field selectors, and returns the list of Backpressures that match those selectors.
func (c *FakeBackpressures) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BackpressureList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(backpressuresResource, backpressuresKind, c.ns, opts), &v1alpha1.BackpressureList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BackpressureList{ListMeta: obj.(*v1alpha1.BackpressureList).ListMeta}
	for _, item := range obj.(*v1alpha1.BackpressureList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested backpressures.
func (c *FakeBackpressures) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(backpressuresResource, c.ns, opts))

}

// Create takes the representation of a backpressure and creates it.  Returns the server's representation of the backpressure, and an error, if there is any.
func (c *FakeBackpressures) Create(ctx context.Context, backpressure *v1alpha1.Backpressure, opts v1.CreateOptions) (result *v1alpha1.Backpressure, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(backpressuresResource, c.ns, backpressure), &v1alpha1.Backpressure{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Backpressure), err
}

// Update takes the representation of a backpressure and updates it. Returns the server's representation of the backpressure, and an error, if there is any.
func (c *FakeBackpressures) Update(ctx context.Context, backpressure *v1alpha1.Backpressure, opts v1.UpdateOptions) (result *v1alpha1.Backpressure, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(backpressuresResource, c.ns, backpressure), &v1alpha1.Backpressure{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Backpressure), err
}

// Delete takes name of the backpressure and deletes it. Returns an error if one occurs.
func (c *FakeBackpressures) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(backpressuresResource, c.ns, name), &v1alpha1.Backpressure{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBackpressures) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(backpressuresResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BackpressureList{})
	return err
}

// Patch applies the patch and returns the patched backpressure.
func (c *FakeBackpressures) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Backpressure, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(backpressuresResource, c.ns, name, pt, data, subresources...), &v1alpha1.Backpressure{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Backpressure), err
}
