name: Nightly Images
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  images:
    name: Docker Images
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.RELEASE_DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.RELEASE_DOCKER_PASS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Module Cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-gomod2-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gomod2-
      - name: Restore Build Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-gobuild-${{ hashFiles('**/*.go') }}
      - name: Setup Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Docker Login
        run: docker login --username "$DOCKER_USER" --password-stdin <<< "$DOCKER_PASS"
      - name: Push images with git sha tag
        env:
          CTR_TAG: latest-main
        run: make docker-push
