apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: azureresources.osm.osm.k8s.io
spec:
  group: osm.osm.k8s.io
  version: v1
  names:
    kind: AzureResource
    plural: azureresources
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            resourceid:
              description: "Resource ID (UUID) of the Azure compute resource. Example: /resource/subscriptions/e3f0/resourceGroups/mesh-rg/providers/Microsoft.Compute/virtualMachineScaleSets/baz"
              type: string
